version: '2' # specify docker-compose version

#services/containers to be run
services:
  angular: # name of the first service
    build: angular/my-app # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
  
  postgres:
    build: postgreSQL
    ports:
      - "5432:5432"
 
  spring: #name of the second service
    build: spring-boot # specify the directory of the Dockerfile
    ports:
      - "8081:8080" #specify ports forewarding
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/docker"
    links:
      - postgres # link this service to the database service


